name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you use for development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: blocks/dist  # Directory containing your build artifacts
          token: ${{ secrets.GITHUB_TOKEN }}
